#!/usr/bin/env bash

function err_report {
    echo "Error on line $1"
}
trap 'err_report $LINENO ' ERR

FLUXO_HELP_MESSAGE="\
GIT-FLUXO

$(tput bold)USAGE$(tput sgr0)

  git fluxo <show | diff | rebase | doctor>
  git fluxo -- <-h|--help>

$(tput bold)ACTIONS$(tput sgr0)
  
  -h | --help      Show detailed instructions

$(tput bold)FLUXO COMMANDS$(tput sgr0)

  <show | s>           Show branches orderes by fluxo
  <diff | d>           Generate code diff files for each fluxo step
  <rebase | r>         Rebase after changing any fluxo previous steps
  <doctor | dr>        Check fluxo health (Are steps synchronized?)
"

. $(cd "$(dirname "$0")" && pwd)"/lib_util.sh"
. $(cd "$(dirname "$0")" && pwd)"/lib_parse_fluxo_branches_file.sh"
. $(cd "$(dirname "$0")" && pwd)"/lib_view.sh"
. $(cd "$(dirname "$0")" && pwd)"/lib_navigate_to_git_repository_root.sh"
. $(cd "$(dirname "$0")" && pwd)"/lib_read_fluxo_file.sh"
. $(cd "$(dirname "$0")" && pwd)"/lib_style.sh"

function fluxo_print_usage {
    echo -ne "\n$FLUXO_HELP_MESSAGE\n"
}

navigate_to_git_repository_root

case "$1" in
-h|--help)
    fluxo_print_usage | less -RF
    exit $?
    ;;
show|s)
    shift
    . $(cd "$(dirname "$0")" && pwd)"/cmd_show_fluxo.sh"
    show_fluxo "$@"
    ;;
drafts|dt)
    . $(cd "$(dirname "$0")" && pwd)"/cmd_show_fluxo.sh"
    shift
    show_fluxo --drafts "$@"
    ;;
diff|d)
    shift
    . $(cd "$(dirname "$0")" && pwd)"/cmd_generate_fluxo_diff_files.sh"
    generate_fluxo_diff_files "$@"
    ;;
rebase|r)
    shift
    . $(cd "$(dirname "$0")" && pwd)"/cmd_rebase_fluxo.sh"
    rebase_fluxo "$@"
    ;;
doctor|dr)
    shift
    . $(cd "$(dirname "$0")" && pwd)"/cmd_fluxo_doctor.sh"
    fluxo_doctor "$@"
    ;;
*)
    fluxo_print_usage
    exit 1
    ;;
esac
